

- name: installing yum requirements
  yum:
    name: ['python3','python-pip','git']
    state: latest

- copy:
    src: /tmp/packer-ansible-provisioner/roles/application/files/pugsite.service
    dest: /etc/systemd/system/pugsite.service
    owner: root
    group: root
    mode: 0644

- name: Ensure group "siteadmin" exists
  ansible.builtin.group:
    name: siteadmin
    state: present

- name: Add the user 'siteadmin'
  ansible.builtin.user:
    name: siteadmin
    group: siteadmin

- pip:
    name: ['virtualenv','Flask']
    executable: pip3
    extra_args: --user
  become: true
  become_user: siteadmin


- name: Create site directory
  ansible.builtin.file:
    path: /pugsite
    state: directory
    recurse: true
    owner: siteadmin
    group: siteadmin
    mode: '0755'

- copy:
    src: /tmp/packer-ansible-provisioner/roles/application/files/pugsite-start.sh
    dest: /pugsite/pugsite-start.sh
    owner: siteadmin
    group: siteadmin
    mode: '0755'

- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/imp14a/python-flask-pugsite.git'
    dest: /pugsite/app
  become: true
  become_user: siteadmin

- name: Pip install application
  ansible.builtin.shell:
    cmd: "pip3 install -e . --user"
    chdir: "/pugsite/app/"
  become: true
  become_user: siteadmin

- name: enable service pugsite and ensure it is not masked
  systemd:
    name: pugsite
    enabled: yes
    masked: no

- name: just force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes

#- name: Change directory permissions
#  ansible.builtin.file:
#    path: /pugsite
#    state: directory
#    recurse: true
#    owner: siteadmin
#    group: siteadmin
#    mode: '0644'