

- name: install the latest version of python3
  yum:
    name: python3
    state: latest

- copy:
    src: /tmp/packer-ansible-provisioner/roles/application/files/pugsite.service
    dest: /etc/systemd/system/pugsite.service
    owner: root
    group: root
    mode: 0644

- copy:
    src: /tmp/packer-ansible-provisioner/roles/application/files/pugsite-start.sh
    dest: /pugsite
    owner: foo
    group: foo
    mode: 0644